---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image using php file
    command: docker build -t myphp:CICD .
    args:
      chdir: /opt/myphp

  - name: create tag to image
    command: docker tag myphp:CICD edu123/myphp:CICD

  - name: loginto docker
    command: docker login --username edu123 --password Edureka@123

  - name: push image on to dockerhub
    command: docker push edu123/myphp:CICD
    
  - name: Do deployment in Docker Swarm cluster
    command: docker service create --name mysvc-ansible --replicas 1 -p 8282:8080 edu123/myphp:CICD
    
  - name: remove docker images form ansible server
    command: docker rmi myproject:CICD edu123/myphp:CICD
    ignore_errors: yes
